name: Test Action 4.x MAC
on:
  workflow_dispatch:
  push:
    branches: [ 'master', 'main', 'prod', 'production' ]

jobs:
  TestAction:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Action
      uses: ./
      with:
        name: test_project.zip
        preset: mac
        projectDir: 4.x_test_project
        package: 'true'
